### ISSUE TITLE
gem_binary in source.rb

### ISSUE THREAD

**Issue by ZepedaMcMillan** [chef-cookbooks/passenger_apache2#31]
I ran into an issue when installing passenger from the chef omnibus installer where the gem_package in source.rb was being installed into /opt/chef/embedded/bin. I manually updated my recipe to include a new attribute called [:passenger][:gem_binary] and added this to the gem_package call at line 46 of source.rb gem_binary node[:passenger][:gem_binary] to fix the issue, but it might be useful to have this baked into your next update. default[:passenger][:gem_binary] = 'gem' is the default value I set. There could be a variety of reasons for using a separate binary though, and with the ability to specify the ruby_bin, it would make sense to be able to specify the gem_binary as well, to ensure that gems get installed in the proper gem folder.

**Comment by tas50** [comment]
A fix for this has been merged into master.  Please give a try and let me know.
