### ISSUE TITLE
Recipe fails on SLES 11.3

### ISSUE THREAD

**Issue by gsecillano** [chef-cookbooks/passenger_apache2#35]
In `recipes/source.rb`, there's no support for the "suse" platform family, so the recipe tries to install apache-prefork-dev (among others), which does not exist in Suse.

The following is the correct list of packages required for Suse:

- apache2-devel
- curl-devel
- openssl-devel
- zlib-devel

**Comment by tas50** [comment]
@gsecillano  I've included basic SUSE support using the packages you mentioned.  Let me know if that works
