### ISSUE TITLE
Passenger Depends on Shell $HOME

### ISSUE THREAD

**Issue by sean-horn** [chef-cookbooks/passenger_apache2#41]
Passenger depends on shell $HOME variable being set.

While chef-client is running in daemonized mode, the children spawned by chef-client do not include $HOME as part of the available shell environment.

As a customer, I would like a workaround for this issue https://github.com/opscode-cookbooks/chef-client/issues/226 to be made in passenger_apache2 if it can be done sooner than in the chef-client cookbook.

**Comment by cheeseplus** [comment]
Closing this as the workaround provided seems sufficient.
