### ISSUE TITLE
First Chef-Client fails on execute[passenger_module] action run

### ISSUE THREAD

**Issue by plorent** [chef-cookbooks/passenger_apache2#48]
I'm running into an issue with version 2.2.3 where the first chef-client run fails on:

   * execute[passenger_module] action run

     ================================================================================
     Error executing action `run` on resource 'execute[passenger_module]'
     ================================================================================

     Mixlib::ShellOut::ShellCommandFailed
     ------------------------------------
     Expected process to exit with [0], but received '1'
     ---- Begin output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
     STDOUT:
     STDERR: /opt/chef/embedded/bin/ruby: No such file or directory -- /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/bin/passenger-install-apache2-module (LoadError)
     ---- End output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
     Ran /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto returned 1

     Resource Declaration:
     ---------------------
     # In /var/chef/cache/cookbooks/passenger_apache2/recipes/source.rb

      50: execute "passenger_module" do
      51:   command "#{node['passenger']['ruby_bin']} #{node['passenger']['root_path']}/bin/passenger-install-apache2-module _#{node['passenger']['version']}_ --auto"
      52:   only_if { node['passenger']['install_module'] }
      53:   # this is late eval'd when Chef converges this resource, and the
      54:   # attribute may have been modified by the `mod_rails` recipe.
      55:   not_if { ::File.exist?(node['passenger']['module_path']) }
      56: end

     Compiled Resource:
     ------------------
     # Declared in /var/chef/cache/cookbooks/passenger_apache2/recipes/source.rb:50:in `from_file'

     execute("passenger_module") do
       action "run"
       retries 0
       retry_delay 2
       guard_interpreter :default
       command "/opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto"
       backup 5
       returns 0
       cookbook_name "passenger_apache2"
       recipe_name "source"
       not_if { #code block }
       only_if { #code block }
     end

 Recipe: chef-client::init_service
   * service[chef-client] action restart
     - restart service service[chef-client]
 Recipe: apache2::default
   * service[apache2] action reload
     - reload service service[apache2]

 Running handlers:
 [2015-04-07T10:05:12+00:00] ERROR: Running exception handlers
 Running handlers complete
 [2015-04-07T10:05:12+00:00] ERROR: Exception handlers complete
 [2015-04-07T10:05:12+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out

The second chef-client run however finishes successfully.
On Ubuntu 12.04, and using cookbook ruby to install ruby 1.9.1

**Comment by reedsutliff** [comment]
have you found a solution? I'm getting this exact error..

**Comment by plorent** [comment]
No. I had to create a AMI with all prerequisites installed and use a wrapper cookbook to just install the application itself.

**Comment by tas50** [comment]
I'm having trouble reproducing this locally.  All of my runs with modern distros and the current cookbook converge without issues.  Can you see if this is still an issue and if so open it back up with details on the platform you're running and the version of chef.

**Comment by justinalcon** [comment]
I have this exact issue as well.  Seems like it has something to do with sourcing bash profiles or re hashing rbenv, but my recipe:

bash '.bashrc' do
  code 'source ~/.bashrc'
end

include_recipe "rbenv::default"
include_recipe "rbenv::ruby_build"

rbenv_ruby "2.2.4" do
  global true
end

bash 'configure git' do
  code 'git config --global user.name "deploy"'
  code 'git config --global user.email "deploy@justin.com"'
end

include_recipe "nodejs"

mysql_service 'justin_DB' do
  port '3306'
  version '5.6'
  initial_root_password ''
  action [:create, :start]
end

include_recipe 'passenger_apache2::mod_rails'

Which gives error (unless I exit and shell back in)

* execute[passenger_module] action run
    
    ================================================================================
    Error executing action `run` on resource 'execute[passenger_module]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
    STDOUT: 
    STDERR: /opt/chef/embedded/bin/ruby: No such file or directory -- /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module (LoadError)
    ---- End output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
    Ran /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto returned 1
    
    Resource Declaration:
    ---------------------
    # In /home/ubuntu/aws-kitchen/cookbooks/passenger_apache2/recipes/source.rb
    
     55: execute 'passenger_module' do
     56:   command "#{node['passenger']['ruby_bin']} #{node['passenger']['root_path']}/bin/passenger-install-apache2-module _#{node['passenger']['version']}_ --auto"
     57:   only_if { node['passenger']['install_module'] }
     58:   # this is late eval'd when Chef converges this resource, and the
     59:   # attribute may have been modified by the `mod_rails` recipe.
     60:   not_if { ::File.exist?(node['passenger']['module_path']) }
     61: end
    
    Compiled Resource:
    ------------------
    # Declared in /home/ubuntu/aws-kitchen/cookbooks/passenger_apache2/recipes/source.rb:55:in `from_file'
    
    execute("passenger_module") do
      action [:run]
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "/opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name :passenger_apache2
      recipe_name "source"
      not_if { #code block }
      only_if { #code block }
    end
    
Recipe: apache2::default
  * service[apache2] action reload
    - reload service service[apache2]

Running handlers:
[2015-12-18T21:07:26+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-18T21:07:26+00:00] ERROR: Exception handlers complete
Chef Client failed. 115 resources updated in 08 minutes 00 seconds
[2015-12-18T21:07:26+00:00] FATAL: Stacktrace dumped to /home/ubuntu/chef-solo/chef-stacktrace.out
[2015-12-18T21:07:26+00:00] ERROR: execute[passenger_module] (passenger_apache2::source line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
STDOUT: 
STDERR: /opt/chef/embedded/bin/ruby: No such file or directory -- /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module (LoadError)
---- End output of /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto ----
Ran /opt/chef/embedded/bin/ruby /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/passenger-4.0.53/bin/passenger-install-apache2-module _4.0.53_ --auto returned 1
[2015-12-18T21:07:26+00:00] FATAL: Chef::Exceptions::Chil
